# http://wiki.ros.org/costmap_2d#costmap_2d.2BAC8-layered.Parameters
local_costmap:
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 0.5
  update_frequency: 2.0
  publish_frequency: 2.0
  rolling_window: true
  static_map: false

  resolution: 0.05
  width: 3.0
  height: 3.0


  #observation_sources: laser_scan_sensor point_cloud_sensor
  observation_sources: point_cloud_sensor
#add after installing LIDAR with /scan topic for laser scan
#  laser_scan_sensor: {
#  data_type: LaserScan, 
#  topic: base_scan, 
#  expected_update_rate: 0.2, 
#  marking: true, 
#  clearing: true}

  # assuming receiving a cloud from rtabmap/obstacles_detection node
  point_cloud_sensor: {
  sensor_frame: base_link,
  data_type: PointCloud2, 
  topic: openni_points, 
  expected_update_rate: 0.5, 
  marking: true, 
  clearing: true,

  #since the robot can be at any height value ranges from
  min_obstacle_height: -99999.0,
  max_obstacle_height: 99999.0}